"""add_recommended_priority_and_confidence_to_triage_stay

Revision ID: b6e03f4cb0d0
Revises: da331438a256
Create Date: 2026-08-30 12:04:37.000560+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e03f4cb0d0'
down_revision: Union[str, None] = 'da331438a256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triage_stays', sa.Column('recommended_priority', sa.String(length=8), nullable=True))
    op.add_column('triage_stays', sa.Column('recommended_confidence', sa.Float(), nullable=True))
    op.create_index(op.f('ix_triage_stays_recommended_priority'), 'triage_stays', ['recommended_priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_stays_recommended_priority'), table_name='triage_stays')
    op.drop_column('triage_stays', 'recommended_confidence')
    op.drop_column('triage_stays', 'recommended_priority')
    # ### end Alembic commands ###
