"""create triage_stays table

Revision ID: da331438a256
Revises: 356060037a52
Create Date: 2026-08-29 12:36:04.469479+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da331438a256'
down_revision: Union[str, None] = '356060037a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_stays',
    sa.Column('stay_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=True),
    sa.Column('hadm_id', sa.BigInteger(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('race', sa.String(length=64), nullable=True),
    sa.Column('arrival_transport', sa.String(length=32), nullable=True),
    sa.Column('disposition', sa.String(length=32), nullable=True),
    sa.Column('age_group', sa.String(length=16), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('resp_rate', sa.Float(), nullable=True),
    sa.Column('o2_sat', sa.Float(), nullable=True),
    sa.Column('sbp', sa.Float(), nullable=True),
    sa.Column('dbp', sa.Float(), nullable=True),
    sa.Column('pain', sa.Float(), nullable=True),
    sa.Column('shock_index', sa.Float(), nullable=True),
    sa.Column('pulse_pressure', sa.Float(), nullable=True),
    sa.Column('mean_arterial_pressure', sa.Float(), nullable=True),
    sa.Column('abnormal_vitals_count', sa.Integer(), nullable=False),
    sa.Column('vitals_missing_count', sa.Integer(), nullable=False),
    sa.Column('missing_history_flag', sa.Boolean(), nullable=False),
    sa.Column('arrival_hour', sa.Integer(), nullable=True),
    sa.Column('night_shift_flag', sa.Boolean(), nullable=True),
    sa.Column('weekend_flag', sa.Boolean(), nullable=True),
    sa.Column('acuity', sa.Integer(), nullable=True),
    sa.Column('predicted_high_acuity', sa.Boolean(), nullable=True),
    sa.Column('predicted_probability', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('stay_id')
    )
    op.create_index(op.f('ix_triage_stays_acuity'), 'triage_stays', ['acuity'], unique=False)
    op.create_index(op.f('ix_triage_stays_age_group'), 'triage_stays', ['age_group'], unique=False)
    op.create_index(op.f('ix_triage_stays_arrival_transport'), 'triage_stays', ['arrival_transport'], unique=False)
    op.create_index(op.f('ix_triage_stays_disposition'), 'triage_stays', ['disposition'], unique=False)
    op.create_index(op.f('ix_triage_stays_predicted_high_acuity'), 'triage_stays', ['predicted_high_acuity'], unique=False)
    op.create_index(op.f('ix_triage_stays_subject_id'), 'triage_stays', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_stays_subject_id'), table_name='triage_stays')
    op.drop_index(op.f('ix_triage_stays_predicted_high_acuity'), table_name='triage_stays')
    op.drop_index(op.f('ix_triage_stays_disposition'), table_name='triage_stays')
    op.drop_index(op.f('ix_triage_stays_arrival_transport'), table_name='triage_stays')
    op.drop_index(op.f('ix_triage_stays_age_group'), table_name='triage_stays')
    op.drop_index(op.f('ix_triage_stays_acuity'), table_name='triage_stays')
    op.drop_table('triage_stays')
    # ### end Alembic commands ###
